@startuml
!include ../clean.skin
skinparam linetype ortho

component "Software Unit" as Unit
component Component
component "Software\nComponent" as SoftwareComponent
component "Hardware\nComponent" as HardwareComponent
component Composition

note right of Component
  aka. "Building Block"
end note

SoftwareComponent -u-|> Component : is a
HardwareComponent -u-|> Component : is a
Composition -d-|> Component : is a
Composition *-d- "1..*" Component : consists\nof
Unit -u-|> SoftwareComponent : is a
@enduml