@startuml
!include seq.skin

!include ../../actors/Customer.plantuml
box "MachineApplication"
	!include ../../participants/vendingmachine/UserInterface.plantuml
	!include ../../participants/vendingmachine/MachineController.plantuml
	!include ../../participants/vendingmachine/RecipeCache.plantuml
	!include ../../participants/foodprinter/PasteContainerConnector.plantuml
end box
!include ../../participants/foodprinter/PasteContainer.plantuml

Customer -> UserInterface : listDishes()
activate UserInterface
UserInterface -> MachineController : listDishes()
activate MachineController
MachineController -> PasteContainerConnector : getInventory()
activate PasteContainerConnector

loop each pasteContainer
	PasteContainerConnector -> PasteContainer : getPasteType()
	activate PasteContainer
	PasteContainer -->> PasteContainerConnector : pasteType
	deactivate PasteContainer
	PasteContainerConnector -> PasteContainer : getFillLevel()
	activate PasteContainer
	PasteContainer -->> PasteContainerConnector : fillLevel
	deactivate PasteContainer
end loop

PasteContainerConnector -->> MachineController : pasteInventory
deactivate PasteContainerConnector
MachineController -> RecipeCache : filterDishes(pasteInventory)
activate RecipeCache

loop each recipe
	RecipeCache -> RecipeCache : canPrepare(recipe,\npasteInvertory)
	activate RecipeCache
	deactivate RecipeCache
end loop

RecipeCache -->> MachineController : dishes
deactivate RecipeCache
MachineController -->> UserInterface : dishes
deactivate MachineController
UserInterface -> UserInterface : renderDishList(dishes)
activate UserInterface 
deactivate UserInterface
UserInterface -->> Customer : dishList 
deactivate UserInterface
@enduml